---
title: "Complex HOC test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(remotes)


remotes::install_github(repo = "digitalemuendigkeit/seminr", ref = "model-viz")
library(seminr)
library(DiagrammeR)
library(dplyr)
```


```{r modelcode}
testdata <- as.matrix(read.csv2("HOC-test-data.csv")[,2:104])


# Make measurement model
mmcc <- constructs(
  composite("Avoidant Maldaptation", multi_items("CCAM", 1:3)),
  composite("Behavioral Intention", multi_items("CCBI", 1:3), mode_B),
  composite("Knowledge", multi_items("CCKN", 1:7), mode_B),
  composite("Perceived Moral Obligation", multi_items("CCPM", 1:3)),
  composite("Perceived Self-Efficacy", multi_items("CCRB", c(1, 4, 7, 10))),
  composite("Perceived Response Efficacy", multi_items("CCRB", c(2, 5, 8, 11))),
  composite("Perceived Response Costs", multi_items("CCRB", c(3, 6, 9, 12))),
  higher_composite("Response Beliefs",
                     c("Perceived Self-Efficacy", "Perceived Response Efficacy", "Perceived Response Costs"),
                     mode_B),
  composite("Subjective Norm Friends", multi_items("CCSN", 1:2), mode_B),
  composite("Subjective Norm Family", multi_items("CCSN", 3:4), mode_B),
  composite("Subjective Norm Colleagues", multi_items("CCSN", 5:6), mode_B),
  higher_composite("Subjective Norm", c("Subjective Norm Friends", "Subjective Norm Family", "Subjective Norm Colleagues"), mode_B),
  composite("Perceived Susceptibility", multi_items("CCTB", 1:3)),
  composite("Perceived Severity", multi_items("CCTB", 4:6)),
  higher_composite("Threat Beliefs",
                   c("Perceived Susceptibility", "Perceived Severity"),
                   mode_B),
  composite("Trusting Beliefs Benevolence", multi_items("CCTR", 1:3)),
  composite("Trusting Beliefs Competence", multi_items("CCTR", 4:6)),
  composite("Trusting Beliefs Integrity", multi_items("CCTR", 7:9)),
  higher_composite("Trusting Beliefs",
                   c("Trusting Beliefs Benevolence", "Trusting Beliefs Competence", "Trusting Beliefs Integrity"),
                   ),
  composite("Distrusting Beliefs Benevolence", multi_items("CCDI", 1:3)),
  composite("Distrusting Beliefs Competence", multi_items("CCDI", 4:6)),
  composite("Distrusting Beliefs Integrity", multi_items("CCDI", 7:9)),
  higher_composite("Distrusting Beliefs",
                   c("Distrusting Beliefs Benevolence", "Distrusting Beliefs Competence", "Distrusting Beliefs Integrity"),
                   )
)

#Make structural model
smcc <- relationships(
  paths(from = c("Avoidant Maldaptation","Perceived Moral Obligation", "Response Beliefs", "Subjective Norm", "Threat Beliefs"),
         to = "Behavioral Intention"),
  paths(from = c("Response Beliefs", "Threat Beliefs"),
        to = "Avoidant Maldaptation"),
  paths(from = c("Knowledge", "Distrusting Beliefs", "Trusting Beliefs"),
        to = c("Response Beliefs", "Threat Beliefs"))
)

testmodel <- estimate_pls(testdata, mmcc, smcc)

# testdata
# mobi <- mobi
# 
#    #seminr syntax for creating measurement model
#    mobi_mm <- seminr::constructs(
#                 reflective("Image",        multi_items("IMAG", 1:5)),
#                 reflective("Expectation",  multi_items("CUEX", 1:3)),
#                 reflective("Quality",      multi_items("PERQ", 1:7)),
#                 reflective("Value",        multi_items("PERV", 1:2)),
#                 reflective("Satisfaction", multi_items("CUSA", 1:3)),
#                 reflective("Complaints",   single_item("CUSCO")),
#                 reflective("Loyalty",      multi_items("CUSL", 1:3))
#               )
#    #seminr syntax for creating structural model
#    mobi_sm <- relationships(
#      paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
#      paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
#      paths(from = "Quality",      to = c("Value", "Satisfaction")),
#      paths(from = "Value",        to = c("Satisfaction")),
#      paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
#      paths(from = "Complaints",   to = "Loyalty")
#    )
# 
#    mobi_pls <- estimate_pls(data = mobi,
#                             measurement_model = mobi_mm,
#                             structural_model = mobi_sm)


```

```{r viscode}
   testmodel %>% seminr::dot_graph() %>% grViz() 
   # mobi_pls %>% seminr::dot_graph() %>% grViz() 
```


