---
title: "Test cases for seminr visualization"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)

library(remotes)


remotes::install_github(repo = "digitalemuendigkeit/seminr", ref = "model-viz")
library(seminr)
library(DiagrammeR)
library(dplyr)
```


```{r modelcode}
mobi <- mobi

   #seminr syntax for creating measurement model
   mobi_mm <- constructs(
                composite("Image",        multi_items("IMAG", 1:5)),
                composite("Expectation",  multi_items("CUEX", 1:3)),
                composite("Quality",      multi_items("PERQ", 1:7)),
                composite("Value",        multi_items("PERV", 1:2)),
                composite("Satisfaction", multi_items("CUSA", 1:3)),
                composite("Complaints",   single_item("CUSCO")),
                composite("Loyalty",      multi_items("CUSL", 1:3)),
                higher_composite("Reputation", c("Image", "Expectation")),
                higher_composite("Goodness", c("Quality", "Value"), weights = mode_B)           
              )
   #seminr syntax for creating structural model
   mobi_sm <- relationships(
     paths(from = "Reputation",        to = c("Satisfaction", "Loyalty", "Goodness")),
     paths(from = "Goodness",      to = c("Satisfaction")),
     paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
     paths(from = "Complaints",   to = "Loyalty")
   )

   mobi_pls <- estimate_pls(data = mobi,
                            measurement_model = mobi_mm,
                            structural_model = mobi_sm)


```

```{r viscode}
   mobi_pls %>% seminr::dot_graph() %>% grViz() 
```


