# Generated by rmake: do not edit by hand
SHELL=/bin/sh
R="$(R_HOME)/bin$(R_ARCH)/Rscript"
RM=rm

.PHONY: all
all: Makefile local github_prepare github
	
local: make.R
	$(R) -e '{' \
	-e '    params <- list(.target = "local", .script = "make.R", .depends = NULL, .task = "all")' \
	-e '    source("make.R")' \
	-e '}'
github_prepare: fetch_github.R
	$(R) -e '{' \
	-e '    params <- list(.target = "github_prepare", .script = "fetch_github.R", .depends = NULL, .task = "all")' \
	-e '    source("fetch_github.R")' \
	-e '}'
github: make.R github_prepare
	$(R) -e '{' \
	-e '    params <- list(.target = "github", .script = "make.R", .depends = "github_prepare", .task = "all")' \
	-e '    source("make.R")' \
	-e '}'
.PHONY: clean
clean: 
	$(RM) local
	$(RM) github_prepare
	$(RM) github
Makefile: Makefile.R
	$(R) -e '{' \
	-e '    params <- list(.target = "Makefile", .script = "Makefile.R", .depends = NULL, .task = "all")' \
	-e '    source("Makefile.R")' \
	-e '}'
