---
title: "Test cases for seminr visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(seminr)
library(DiagrammeR)
```


```{r modelcode}
mobi <- mobi

   #seminr syntax for creating measurement model
   mobi_mm <- constructs(
                reflective("Image",        multi_items("IMAG", 1:5)),
                reflective("Expectation",  multi_items("CUEX", 1:3)),
                reflective("Quality",      multi_items("PERQ", 1:7)),
                reflective("Value",        multi_items("PERV", 1:2)),
                reflective("Satisfaction", multi_items("CUSA", 1:3)),
                reflective("Complaints",   single_item("CUSCO")),
                reflective("Loyalty",      multi_items("CUSL", 1:3))
              )
   #seminr syntax for creating structural model
   mobi_sm <- relationships(
     paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
     paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
     paths(from = "Quality",      to = c("Value", "Satisfaction")),
     paths(from = "Value",        to = c("Satisfaction")),
     paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
     paths(from = "Complaints",   to = "Loyalty")
   )

   mobi_pls <- estimate_pls(data = mobi,
                            measurement_model = mobi_mm,
                            structural_model = mobi_sm)


```



Theme settings
```{r}
ifontsize <- 9
iwidth <- strwidth('CUSA9', font = ifontsize, units = 'in') + 0.1
iheight <- strheight('CUSA9', font = ifontsize, units = 'in') + 0.1

cfontsize <- 12
cwidth <- strwidth('Image_x_Expectation', font = cfontsize, units = 'in') + 0.3
cheight <- strheight('Image_x_Expectation', font = cfontsize, units = 'in') + 0.3
```



```{r pls_plot2}

my_theme <- create_theme(item_style = createItemStyle(
    fontsize = ifontsize, 
    width = iwidth, height = iheight, 
    color = "black", fill = "lightgoldenrodyellow"),
  
  # we can style the construct appearance
  construct_style = createConstructStyle(
    fontsize = cfontsize, 
    width = cwidth, height = cheight, 
    color = "black", fill = "lightcyan"),
  
  # we can style the outer weight edges
  outer_weight_style = createOuterWeightStyle(color = "dimgray"),
  
  # we can style the inner weight edges
  inner_weight_style = createInnerWeightStyle(color = "black", fontsize = 12)
  )

mobi_pls %>% plot_model(
  # we can have a title
  title = "PLS-SEM Plot with interactions",
  
  # we can style the item appearance
  theme = my_theme  
  ) %>% 
  grViz()
```



```{r viscode}
  plot_model(mobi_pls) %>% DiagrammeR::grViz()
```


